---
- name: Linux - Allow SSH from Tailscale in UFW (Debian)
  community.general.ufw:
    rule: allow
    src: "100.64.0.0/10"
    port: ssh
    proto: tcp
  when: ansible_facts['os_family'] == "Debian"
  notify: Reload ufw
