---
- name: Linux - update and upgrade all packages (Debian)
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    purge: true
    allow_downgrades: true
  when:
    - ansible_facts['os_family'] == "Debian"
    - not (security_hardening_verify_only | default(false))
  tags:
    - security
    - security:os_baseline
    - security:update

- name: Linux - ensure dnf python bindings (RedHat)
  ansible.builtin.raw: dnf install -y python3-libdnf5
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['virtualization_type'] not in ['docker', 'container']
    - not (security_hardening_verify_only | default(false))
  changed_when: false
  tags:
    - security
    - security:os_baseline
    - security:update

- name: Linux - update all packages (RedHat)
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['virtualization_type'] not in ['docker', 'container']
    - not (security_hardening_verify_only | default(false))
  tags:
    - security
    - security:os_baseline
    - security:update
    - skip_ansible_lint
