---
- name: Linux - update and upgrade all packages (Debian)
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    purge: true
    allow_downgrades: true
  when:
    - ansible_facts['os_family'] == "Debian"
    - not (security_hardening_verify_only | default(false))
  tags:
    - security
    - security:os_baseline
    - security:update
