---
- name: Cloudflared | Install | Detect OS family
  ansible.builtin.set_fact:
    cloudflared_pkg_type: "{{ 'deb' if ansible_facts['os_family'] == 'Debian' else 'rpm' if ansible_facts['os_family'] == 'RedHat' else 'tar.gz' }}"
    cloudflared_arch: "{{ 'amd64' if ansible_facts['architecture'] == 'x86_64' else 'arm64' if ansible_facts['architecture'] in ['aarch64', 'arm64'] else '386' }}"
    cloudflared_release_url: "https://github.com/cloudflare/cloudflared/releases/download/{{ cloudflared_version }}"

- name: Cloudflared | Install | Debian/Ubuntu
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Cloudflared | Install | Download package
      ansible.builtin.get_url:
        url: "{{ cloudflared_release_url }}/cloudflared-linux-{{ cloudflared_arch }}.deb"
        dest: "/tmp/cloudflared-linux-{{ cloudflared_arch }}.deb"
        mode: "0644"

    - name: Cloudflared | Install | Install package
      ansible.builtin.apt:
        deb: "/tmp/cloudflared-linux-{{ cloudflared_arch }}.deb"
        state: present
      notify: Restart cloudflared
  become: true

- name: Cloudflared | Install | RedHat/Fedora
  when: ansible_facts['os_family'] == 'RedHat'
  block:
    - name: Cloudflared | Install | Download package
      ansible.builtin.get_url:
        url: "{{ cloudflared_release_url }}/cloudflared-linux-{{ cloudflared_arch }}.rpm"
        dest: "/tmp/cloudflared-linux-{{ cloudflared_arch }}.rpm"
        mode: "0644"

    - name: Cloudflared | Install | Install RPM
      ansible.builtin.yum:
        name: "/tmp/cloudflared-linux-{{ cloudflared_arch }}.rpm"
        state: present
      notify: Restart cloudflared
  become: true

- name: Cloudflared | Install | Cleanup temp files
  ansible.builtin.file:
    path: "/tmp/cloudflared-linux-{{ cloudflared_arch }}.{{ cloudflared_pkg_type }}"
    state: absent
