---
security_hardening_profile: cis_paranoid

# Global switches
security_hardening_apply_network_firewall: true
security_hardening_enable_auditd: true
security_hardening_verify_only: false

# Linux SSH settings
security_hardening_ssh_port: 22
security_hardening_permit_root_login: "no"
security_hardening_password_auth: "no"

# Windows settings
security_hardening_windows_rdp_enabled: false
security_hardening_windows_allowed_ports:
  - 5985
  - 5986
