---
- name: Apply Server Configuration
  hosts: all
  become: false
  gather_facts: true
  vars_files:
    - ../vars/homelab_public.yml
  vars:
    packages_install_gui: false

  roles:
    - role: keyvault_secrets
      tags: ['keyvault', 'secrets', 'always']

    - { role: tailscale, tags: ["tailscale"], become: true }
    - { role: security_hardening, tags: ["security"], become: true }
    - role: chezmoi
      tags: ["chezmoi"]
      chezmoi_home: "{{ ansible_facts['user_dir'] }}"
      chezmoi_repo: "{{ dotfiles_repo }}"
      chezmoi_branch: "main"
      chezmoi_source_path: "{{ ansible_facts['user_dir'] }}/.local/share/chezmoi"
      chezmoi_force_apply: true
      become: false
