---
backup_restore_snapshot: ""
backup_restore_stacks:
  - torrent-client
  - pihole
  - portainer
  - couchdb
  - docuseal
  - firefly
  - monica
  - openwebui
  - paperless_ngx
  - paperless_ai
  - n8n
  - resume-matcher
  - immich
  - jellyfin
  - monitoring
  - authentik
  - uptime-kuma
