---
- name: Windows - OS baseline hardening
  ansible.builtin.include_tasks: os_baseline.yml
  tags:
    - security
    - security:os_baseline
    - security:windows

- name: Windows - authentication and access hardening
  ansible.builtin.include_tasks: auth_access.yml
  tags:
    - security
    - security:auth
    - security:windows

- name: Windows - network and firewall hardening
  ansible.builtin.include_tasks: network_firewall.yml
  tags:
    - security
    - security:network
    - security:windows

- name: Windows - audit and logging hardening
  ansible.builtin.include_tasks: audit_logging.yml
  tags:
    - security
    - security:audit
    - security:windows

- name: Windows - secure services hardening
  ansible.builtin.include_tasks: secure_services.yml
  tags:
    - security
    - security:services
    - security:windows

- name: Windows - verification
  ansible.builtin.include_tasks: verify.yml
  tags:
    - security
    - security:verify
    - security:windows
